sudo: required
language: clojure
jdk:
  - openjdk11
services:
  - docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "UKy9JdaRYCNpWAa8mfUx1kYTwvXx289IBgP2B9cb28yZFyHtIj/Z7TRYbKc50fwhbYC/9KPhwFIHuBJpRF5xBHWB/2RkdOtcm5fuzGa6Vl9UbHt6+hh7mSlWdYnDgBJm5yqXu4stFJX4Z94Q7hrlQZIXDfDZSiReGJ2PZi2PTkAyyCeblZG+HPC6QFTZaPwhO2SxdIavuscvpGtuhWGCVjFTrdxoa3+cOGSb7e6Vcrpq+viVpp/LhSGnu4W6XKyggJnkzNg+DoqAFwJXVDWfu8VGQl3llH3cwKi5MJ9RUFi0b5wwLNN/oa+Rq6yvqYZoIw2jaCU5O+POE+TijwzedKSREKpEz+tWIzrb8MwYYCVX/DydyER33RUA1OOn3pxdSblu1ehQoiqK2rsKJMIv3qcY2VJGCEpEUXgzXmhliJ9p2ViS2uEz0QFVAEx2p4/Z2yWemodcq2fI8t3Z7AHYtW1d3oZmhUhRLKfId4DJ2+gJxgd0Kz0pFFhf/OL0UZxWQI1XIlmABn++fJdnd8X2yecr+DNUbeiPkcq+OWLbdovtEb6fJEZ8Vp1LdMdQ+7UArUOlWfnUxjalM8twWs/r7JblxFzTgrEhLK0Ts7RFDvnT9McukTeTBw8BnP2G8sunjd2yRLdOx3BUISxqeRaQrrLC2iWnZQULBjGwfy1NWOE="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Qvw8fA8pJBj+BqpYQ0N/C6YAgaxhyrNcVfEEmK7cHyTmdAuMdJR5h/wXkNilwfjPfM9w6rtIskRHejuiCiSucmIzex/tDRSJejD0mhm/ZMqW/lzlTxBRIgfWYHJHH9AUODguQ38urMiHH/bin3QTAdeAJis+RjxJ/Zr/ydbw4F51+tV6Ep3iWZLi7GmKa4l0bzdlm6ML6Y7+tK4AK2MnBYuQxURbwlw9YFFxR3IPI2dmSy2/kSaR0bUzkPenLFyq4kqsimryFYMeU8b/wpItbTTdv2MitsZo/DKw51V6TU9p6EV9jCblR1QCD0ab5z+5wXgUkvMoOYv2TN672V1+eqU9p26+VZ33MjbBapRqFld/ZfahYgjE7eei40dbKYFwvhd0zJLcI66MKQdWfOi+UQ/oI9c4Dg5ydMA6gSsbJNfVMvC1SQOekKGrJkwTIkiuExUXMQ9I1Q+AdCrUDrfP1tXiePh09ivj6StW2+CyYPE7zdufeI1Dq8w6ryHYIurwcmz+tGrvRDlkfrItrIST7xKPmL9Ue2bY0EDHZpUI79q6afcTxNp+oDjn4uF5OOPXDMKQg/SMby5ZhmExk00wS+lutFpPcPNmcbtP35T8ZenZQA1g3YfMtCuM6+7DjdOc6REl/kE40E0WGQCdxSE5BS0Fl+QnisQQ/BBpWOJt4Zo="
    # ARTIFACTORY_USERNAME
    - secure: "Ph4Ybt9WoKJQsdmVCaAHwDZ7yUfexXNgQTPTkARXx8nLJc200bM8qPMruj5wWX1ByYufr+R9AJbBSXq//1r4a+2SDRiuVOnEe8GveiCWCij89KAp6NlL5xnX/s0cmxW5tBoRwXTRMNCCn33nfFAaLGsgwCVMYlvpZBSVy3n35PPyMwIe2PNE2aBa+pAVp+1/M0kdcM75SwC3VcEs+Vrh3nnQjARHAHRN2cyf3OWZ0QUt7kDsqdgO1efaEItkCoD8NpdxAVwKCBgHCvOsiDdiugUcaEVi+aWNVybupd4wGYYVY38WZclsNEw/Et0lmTfo0/TXbjs6AlOaplr5sFZ3GzGEo9xghmQKCUmSH/sqIfwFuRqqorujaXCOJprhLHr5Z6lOLZbImfAWdWAR7M4ZYPNxBGHs4GB9LkF3GSwaILNEB2ULCgitPjD/r5wkjV6weN+Kvjz7Vs2d6iwxwiihaOC0wP2VHZEXn7oW8C93lhw957aiDomv8BZoS7trqT0+Be24lq/Wm/feTDqzznfib/PiXnmKXL97H2trcLno/jfiQa4WltoPtWocZnwhZf2sxs23FHVSpVqlUjfsQHvnprKAw2pz9wOudAMZXw1Dg8491pHN9JHv2Z7K4BADUJwQjmHaGr9IO2RRKmJ4Gzt/jdmPIa1TnxjMnSa9fQ0V/9Q="
    # ARTIFACTORY_PASSWORD
    - secure: "em5xC5tATKyqt6MDXqTm+W938jv4p2EtNxNn3LIjHtaGL3UCdjNXZKrnVmETWo3EWhECIWdSfnmMLm6AEO0xOoS4/xAoz6JBbbDjELb8kg24NN0az7SloMPeJtzk3tn3YcAQwQtTh8SxSA+s/iYpZi8p39U2tMLQycCuaU7LYyP3/a1lhg1p/HuX/6OD6M8EExW27HvIyUZphpsdiLA0jrfMiijIRvUFKvBD7xghf2WFvOW2KohBuaTppray5Or1pe93LDDN3PHvnwAxeWof4zVw6H9AaVnCIwt3Ep+4M2YZ2uDBY868DVnBJhtByWYLNTOFA6gQ0VNe1fcS+hTqohuM4M714lH/zbBxcSvTsL2R6BCAvoYoJRoexiNTdiUlw0qPJDwPJBFPfdKkVgBD2cyhprcTJi9vQrpcaNZG9sroklb6DJP9HtYCssbTgioPkH1a64g5P5yT4uBPoqGSvAv2+vVJqI/oRFiSTNBXt4TBRjv/k0LCm6QvANx7opOcvO6+VNygeI4zztVu1Dzpozw1Hb3H9J5To19QQSY77GI+ZS/j9yMhVI/c3k0zzFD/bXBRdARJCPZydCcM0tNoPhOx3rmS92SxlR1lRGAHN31Hn4qhPptSXFzHUavqdQibN52FXnUa7K/WwlKjYrQZ2O+h8NtkP17P/r836xnYnLg="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="kouta-indeksoija"

before_script:
  - docker pull localstack/localstack:0.10.2

script:
  - lein -U ci-test
  - lein uberjar

  - mv target/kouta-indeksoija-*-standalone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh ${ARTIFACT_NAME}

deploy:
  - provider: script
    script: lein deploy
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: lein deploy
    skip_cleanup: true
    on:
      branch: KTO-652-indeksi-sorakuvauksille
  - provider: script
    script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
    on:
      all_branches: true
